import numpy as np 
from rk import * 
import pyglet as pg 
import draw as d 
from body import Body

bodies = 3 # number of bodies
t_final = 10000
# initial conditions: [ [x, y, z], [v_x, v_y, v_z], [m, 0, 0] ] per row (for 0-th row, its [ [x, y, z], [vx, vy, vz], [ax, ay, az] ]) 

# NOTE: Initial conditions for testing generated by an LLM 

# The Montgomery-Chenciner Figure-8 Orbit
# w = 5 # width of screen
# initial = np.array([
#     [ [0, 0, 0], [0, 0, 0], [0, 0, 0] ], # CM
#     [ [97.000436, -24.308753, 0], [0.466203685, 0.432365730, 0], [100, 0, 0] ], # B1
#     [ [-97.000436, 24.308753, 0], [0.466203685, 0.432365730, 0], [100, 0, 0] ], # B2
#     [ [0.0, 0.0, 0.0], [-0.93240737, -0.86473146, 0], [100, 0, 0] ],               # B3
# ]) # Add B-n rows for the Bn-th body

###
# Hierarchical Orbit (Sun, Earth, Moon equivalent)
w = 15
initial = np.array([
    [ [0, 0, 0], [0, 0, 0], [0, 0, 0] ], # CM
    [ [0, 0, 0], [0, -0.0585, 0], [10000, 0, 0] ],   # Star (massive, slow)
    [ [300, 0, 0], [0, 5.7735, 0], [100, 0, 0] ],    # Planet (medium mass/distance)
    [ [320, 0, 0], [0, 8.0095, 0], [1, 0, 0] ],       # Moon (tiny mass, tightly orbiting planet)
])
###

###
# Lagrange Equilateral Triangle (Star, Gas Giant, Trojan)
# w = 20
# initial = np.array([
#     [ [0, 0, 0], [0, 0, 0], [0, 0, 0] ], # CM
#     [ [-2.97, 0, 0], [0, -0.057, 0], [10000, 0, 0] ],             # Central Star
#     [ [297.03, 0, 0], [0, 5.744, 0], [100, 0, 0] ],               # Gas Giant
#     [ [147.03, 259.81, 0], [-5.025, 2.844, 0], [1, 0, 0] ],        # Trojan Asteroid at L4
# ])
###

###
# 2-body test (based on Lagrange Equilateral Triangle)
# w = 10
# initial = np.array([
#     [ [0, 0, 0], [0, 0, 0], [0, 0, 0] ], # CM
#     [ [-2.97, 0, 0], [0, -0.057, 0], [10000, 0, 0] ],
#     [ [297.03, 0, 0], [0, 5.744, 0], [100, 0, 0] ],
# #    [ [147.03, 259.81, 0], [-5.025, 2.844, 0], [1, 0, 0] ],
# ])
###

###
# 4-body test
# Hierarchical Double-Binary System
# w = 10
# initial = np.array([
#     [ [0, 0, 0], [0, 0, 0], [0, 0, 0] ],               # CM Reference
#     [ [-210, 0, 0], [0, -2.0811388, 0], [100, 0, 0] ], # B1 (Left Pair, Outer Star)
#     [ [-190, 0, 0], [0, 1.0811388, 0], [100, 0, 0] ],  # B2 (Left Pair, Inner Star)
#     [ [190, 0, 0], [0, -1.0811388, 0], [100, 0, 0] ],  # B3 (Right Pair, Inner Star)
#     [ [210, 0, 0], [0, 2.0811388, 0], [100, 0, 0] ]    # B4 (Right Pair, Outer Star)
# ])
###

### 3-body  test with 1 collision and 1 in orbit
# w = 10
# initial = np.array([
#     [ [0, 0, 0], [0, 0, 0], [0, 0, 0] ], # CM
#     [ [97, 29, 0], [0.35, -0.8,  0], [1000, 0, 0] ], # B1
#     [ [192, -84, 0], [-0.3, 0.2, 0], [1000, 0, 0] ], # B2
#     [ [0.0, 0.0, 0.0], [-0.3, -1.8, 0], [100, 0, 0] ],               # B3
# ])
###

### Stable-ish hierarchical system with Trojans and moons.
# w = 25
# initial = np.array([
#     [ [0, 0, 0], [0, 0, 0], [0, 0, 0] ],  # CM
#
#     # Central star, slightly offset so total position/momentum are near centered
#     [ [0.263386, -0.711634, 0], [0.006759, -0.042767, 0], [20000, 0, 0] ],  # B1 Star
#
#     # Inner planet + moon
#     [ [160.000000, 0.000000, 0], [0.000000, 11.180340, 0], [30, 0, 0] ],    # B2 Inner Planet
#     [ [172.000000, 0.000000, 0], [0.000000, 12.761479, 0], [1, 0, 0] ],     # B3 Inner Moon
#
#     # Gas giant + two moons
#     [ [340.000000, 0.000000, 0], [0.000000, 7.669650, 0], [120, 0, 0] ],    # B4 Gas Giant
#     [ [368.000000, 0.000000, 0], [0.000000, 9.739847, 0], [2, 0, 0] ],      # B5 Inner Giant Moon
#     [ [385.000000, 0.000000, 0], [0.000000, 9.302643, 0], [0.3, 0, 0] ],    # B6 Outer Giant Moon
#
#     # Gas giant Trojans near L4/L5
#     [ [170.000000, 294.448637, 0], [-6.642112, 3.834825, 0], [0.5, 0, 0] ], # B7 L4 Trojan
#     [ [170.000000, -294.448637, 0], [6.642112, 3.834825, 0], [0.5, 0, 0] ], # B8 L5 Trojan
#
#     # Outer planet + moon, placed at an angle for visual variety
#     [ [-610.800204, 222.313093, 0], [-1.897186, -5.212477, 0], [80, 0, 0] ], # B9 Outer Planet
#     [ [-631.473441, 229.837536, 0], [-2.549393, -7.004400, 0], [1.5, 0, 0] ],# B10 Outer Moon
#
#     # Distant ice body
#     [ [-450.000000, -779.422863, 0], [4.082483, -2.357023, 0], [5, 0, 0] ],  # B11 Ice Body
# ])
###


G = 1 # 6.674e-11
fps = 60*200 # tick rate

def to_CM_ref(r_abs, vel_abs, mass, CM_only=False):
    bodies = len(r_abs) # number of true bodies + 1 

    # calculate center of mass
    r_cm = np.zeros(3) # [x_cm, y_cm, z_cm]
    for i in range(3):
        r_cm[i] = np.dot(r_abs[1:,i], mass) / np.sum(mass) # i+1 to leave out CM values

    if CM_only:
        return r_cm 

    # get positions WRT CM
    # r = np.array([]) 
    r = np.zeros_like(r_abs) 
    r[0] = r_abs[0] # preserves position of CM across function calls
    for i in range(1, bodies):
        r[i] = r_abs[i] - r_cm # Fill the rows directly

    # get velocities WRT CM (non-relativistic)
    vel = np.zeros_like(vel_abs)
    vel[0] = vel_abs[0] # preserves velocity of CM across function calls
    for i in range(1, bodies):
        vel[i] = vel_abs[i] - vel_abs[0] # Fill the rows directly

    return r, vel, r_cm

# converts to absolute reference frame (absolute = origin)
def to_abs_ref(r, vel, r_cm):
    bodies = len(r)

    # get absolute positions
    r_abs = np.zeros_like(r)
    r_abs[0] = r[0] # preserves CM position across function calls
    for i in range(1, bodies):
        r_abs[i] = r[i] + r_cm + r[0]

    # get absolute velocities (non-relativistic)
    vel_abs = np.zeros_like(vel)
    vel_abs[0] = vel[0] # preserves value across function calls
    for i in range(1, bodies):
        vel_abs[i] = vel[i] + vel_abs[0]

    return r_abs, vel_abs

# gravity diff eq in CM reference
def fg(t, b1_old, bn_vals, mass):
    # b1_old = [ [x1, y1, z1], #these are the ones that will be modified
    #             [vx1, vy1, vz1] ]
    # bn_vals = [ [x2, y2, z2],   #B2
    #             [xn, yn, zn], ] #Bn
    # mass = [m1, m2, m3, ..., mn]

    def mag(vec): # returns magnitude of vec 
        sum = 0
        for e in vec:
            sum += e**2
        return np.sqrt(sum)

    b1_next = np.zeros((2,3))

    b1_next[0] = b1_old[1]
    for i in range(len(mass)):
        delta_r = b1_old[0] - bn_vals[i]

        # Handles collisions
        # 1 is the width of the bodies. change this based on size of bodies
        # NOTE: Mass isn't conserved; the mass of one of the w bodies involved in the collisions gets destroyed
        if (mag(delta_r) < 1):
            b1_next[0] = 0
            b1_next[1] = 0

            continue
        b1_next[1] += -G*mass[i]*(delta_r) / (mag(delta_r))**3

    return b1_next

###  WARN: EXPERIMENTAL - switch to energy and momentum conservation baseed calc
# def energy_momentum(t, body_objects_next, body_objects_prev, energy=None):
#     # minimize potential energy (gradient descent)
#     # compensate for decrease in energy by increasing kinetic energy to keep total energy constatnt 
#     # momentum must be conserved at all times 
#     tolerance = 1e-6
#
#     # compute potential energy
#     potential_i = 0 
#     kinetic_i = 0 
#     for i in range(len(body_objects_prev)):
#         counter = 0 
#         for j in 
#     return 
###

d.__init__(1280, 720, 64*w, 36*w)

initial_cm = initial.copy()
pos_next = np.zeros((bodies, 2, 3))
t_curr = 0
body_objects = []
body_objects_old = []

for i in range(bodies):
    color = np.random.randint(0, 256, 3)
    color = tuple(color)
    body = Body(position=initial[i+1, 0], velocity=initial[i+1, 1], mass = initial[i+1, 2][0], color = color, radius=5.0)
    body_objects = np.append(body_objects, body)
    body_objects_old = np.append(body_objects_old, body)

def update(dt):
    global initial_cm, pos_next, t_curr

    if (t_curr > t_final):
        return

    d.start_frame()
   # d.draw_axes()

    # switch to CM reference (update after movement)
    r_abs = initial[:,0]
    vel_abs = initial[:,1]
    mass = initial[1:,2][:,0] # leave row 0, col 2 of initial since it is acceleration values of CM  
    r, vel, r_cm = to_CM_ref(r_abs, vel_abs, mass)

    # NOTE: initial_cm still has un-changed initial[0] corresponding to CM_0 values WRT absolute reference frame
    initial_cm[:,0] = r
    initial_cm[:,1] = vel

    n = len(initial_cm) - 1 # number of bodies
    t = 0 
    for i in range(n):
        counter = 0

        # format data in the way fg() expects 
        b1_old = np.zeros((2,3))
        b1_old[0] = initial_cm[i+1, 0] # position of i-th body
        b1_old[1] = initial_cm[i+1, 1] # velocity of i-th body
        bn_mass = np.zeros(n-1)
        bn_vals = np.zeros((n-1,3))

        for j in range(n):
            if (i != j):
                bn_vals[counter] = initial_cm[j+1, 0]
                bn_mass[counter] = mass[j]
                counter += 1 

        # call rk to evaluate next pos for b1 (outside j-loop)
        t, b1_next = rk_single(fg, t_curr, b1_old, bn_vals, bn_mass)
        pos_next[i] = b1_next #1st column contains positions, and 2nd contains velocities

        # draw objects
        # print(pos_next[i, 0, 0], pos_next[i, 0, 1]) # DEBUG
        d.draw(x_pos=pos_next[i, 0, 0], y_pos=pos_next[i, 0, 1], color=body_objects[i].color, radius=body_objects[i].radius)

    d.end_frame()

    initial_cm[1:,0] = pos_next[:,0]
    initial_cm[1:,1] = pos_next[:,1]

    # switch to absolute reference frame
    r = initial_cm[:,0]
    vel = initial_cm[:,1]
    r_abs, vel_abs = to_abs_ref(r, vel, r_cm)

    # update initial with new values for next time step
    t_curr = t 
    initial[:,0] = r_abs
    initial[:,1] = vel_abs

pg.clock.schedule_interval(update, 1/fps)
d.__run__()
###
